name: CI/CD with Docker Compose Linux Host

on:
  push:
    branches:
      - main
    # paths:
    #   - "configs"
    #   - "docker"
    #   - "local_mount"
    #   - "third_party_pkgs"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}/ros2_humble_development
  TAG: amd64

jobs:
  build-and-test:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.3.0 #v3.1.1
        with:
          cosign-release: "v2.2.2"

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      #- name: Build and start Docker Compose services
      #  run: docker compose -f compose_linux.yaml up -d --build

      #- name: Wait for services to be healthy (optional, but recommended)
      #  # You can use a dedicated action or a script to wait for health checks
      #  # Example using a simple sleep (adjust as needed for your application)
      #  run: sleep 30

      #- name: Test noVNC is up
      #  run: |
      #    SERVICE_URL="http://localhost:3080"
      #    EXPECTED_RESPONSE="200"
      #    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL)
      #    if [ "$RESPONSE" == "$EXPECTED_RESPONSE" ]; then
      #        echo "Test Passed: Service returned expected response."
      #        echo "Expected: $EXPECTED_RESPONSE"
      #        echo "Actual: $RESPONSE"
      #        exit 0
      #    else
      #        echo "Test Failed: Service response did not match expected response."
      #        echo "Expected: $EXPECTED_RESPONSE"
      #        echo "Actual: $RESPONSE"
      #        exit 1
      #    fi

      #- name: Test code-server is up
      #  run: |
      #    SERVICE_URL="http://localhost:3081"
      #    EXPECTED_RESPONSE="200"
      #    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL)
      #    if [ "$RESPONSE" == "$EXPECTED_RESPONSE" ]; then
      #        echo "Test Passed: Service returned expected response."
      #        echo "Expected: $EXPECTED_RESPONSE"
      #        echo "Actual: $RESPONSE"
      #        exit 0
      #    else
      #        echo "Test Failed: Service response did not match expected response."
      #        echo "Expected: $EXPECTED_RESPONSE"
      #        echo "Actual: $RESPONSE"
      #        exit 1
      #    fi

      #- name: Test sshd is up
      #  run: |
      #    EXPECTED_RESPONSE="1"
      #    RESPONSE=$(netstat -an | grep 0.0.0.0:3022 | grep tcp | grep LISTEN | wc -l)
      #    if [ "$RESPONSE" == "$EXPECTED_RESPONSE" ]; then
      #        echo "Test Passed: Service returned expected response."
      #        echo "Expected: $EXPECTED_RESPONSE"
      #        echo "Actual: $RESPONSE"
      #        exit 0
      #    else
      #        echo "Test Failed: Service response did not match expected response."
      #        echo "Expected: $EXPECTED_RESPONSE"
      #        echo "Actual: $RESPONSE"
      #        exit 1
      #    fi

      #- name: Check running containers (optional for debugging)
      #  run: docker ps -a

      #- name: Stop and remove containers
      #  run: docker compose -f compose_linux.yaml down

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
